"""create book_ratings table

Revision ID: 01ebda34a0c1
Revises: 
Create Date: 2020-06-03 10:25:13.359356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ebda34a0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('only_one_book_rating_per_user', 'book_ratings', ['book_id', 'email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('only_one_book_rating_per_user', table_name='book_ratings')
    op.drop_table('book_ratings')
    # ### end Alembic commands ###
